apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Note: These are base64 encoded values. In production, use proper secret management
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ= # "password" encoded
  MONGO_ROOT_USERNAME: YWRtaW4= # "admin" encoded
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # "password" encoded
  POSTGRES_USER: cG9zdGdyZXM= # "postgres" encoded
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q= # "guest" encoded
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q= # "guest" encoded
