apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Note: These are base64 encoded values. In production, use proper secret management
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ= # "password" encoded
  MONGO_ROOT_USERNAME: YWRtaW4= # "admin" encoded
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # "password" encoded
  POSTGRES_USER: cG9zdGdyZXM= # "postgres" encoded
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q= # "guest" encoded
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q= # "guest" encoded
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvOjI3MDE3L21hcHN0b3JlP2F1dGhTb3VyY2U9YWRtaW4= # mongodb://admin:password@mongo:27017/mapstore?authSource=admin
