import "./globals.css";
import type { Metadata } from "next";
import { Anek_Gurmukhi } from "next/font/google";
import NavBar from "./NavBar";

const inter = Anek_Gurmukhi({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
