apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger
  ports:
    - port: 50001
      targetPort: 50001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: logger-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50001
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
