apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-storage
  template:
    metadata:
      labels:
        app: map-storage
    spec:
      containers:
        - name: map-storage
          image: aqtran/map-storage-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongo:27017/mapstore?authSource=admin"
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_PASSWORD
