apiVersion: v1
kind: Service
metadata:
  name: map-storage-service
spec:
  selector:
    app: map-storage
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: map-storage
  template:
    metadata:
      labels:
        app: map-storage
    spec:
      containers:
        - name: map-storage
          image: map-storage-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
