apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-storage
  template:
    metadata:
      labels:
        app: map-storage
    spec:
      containers:
        - name: map-storage
          image: aqtran/map-storage-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: map-storage-service
spec:
  selector:
    app: map-storage
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
