apiVersion: v1
kind: Service
metadata:
  name: solver-service
spec:
  selector:
    app: solver
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solver
  template:
    metadata:
      labels:
        app: solver
    spec:
      containers:
        - name: solver
          image: solver-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
