apiVersion: v1
kind: Service
metadata:
  name: solver-service
spec:
  selector:
    app: solver
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solver
  template:
    metadata:
      labels:
        app: solver
    spec:
      containers:
        - name: solver
          image: aqtran/solver-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
